### ISSUE TITLE
Extend database with agency name data

### ISSUE THREAD

**Issue by Japoivvb** [NabilHG/-nabil_hajjoune_uf3_p1#2]
1.create a feature branch to fix it

2.alter table actors to add a field to save agency and seed it as you consider

3.set issue label as development to be tracked

4.commit message with #numberIssue verb(in 3rd person) + details

5.create pull request and merge to main branch mention me with @name when it is ready in order to close issue please

**Comment by Japoivvb** [comment]
It was requested to add field to actors table but films table, I close now the issue but check again next time

**Comment by NabilHG** [comment]
Good morning, Jose.

If I had understood it wrong, correct me please. The feature I was supposed to do in the actor's table was to add there a new field. At the beginning, I have done it wrong because I did it in the film's table. When I realized my mistake, I fix it in a branch called “hotfix2”, that I merged into the main one.

Sorry for the misinterpretation, and thanks for the comprehension.

**Comment by Japoivvb** [comment]
OK, I see now the last fix direct in main branch with the defined change, my fault I should have checked final last source version. Issue does not need to be reopened.

**Comment by NabilHG** [comment]
No worries, it was my fault for not paying enough attention. Thanks for the comprehension.
